### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by Finkes** [coach-plus/server#15]
I'm not yet sure when this happens. I guess it relates to the "forgot password workflow" for users that do not exist

```
2020-02-09T13:53:26.078Z - error:  message=Cannot read property 'password' of null, stack=TypeError: Cannot read property 'password' of null
    at UserApi.<anonymous> (/app/server/dist/api/user.js:368:90)
    at Generator.next (<anonymous>)
    at fulfilled (/app/server/dist/api/user.js:13:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by Finkes** [comment]
it happens when a user who is not yet registered tries to login

**Comment by Finkes** [comment]
solved
